# Naive Dockerfile using Python and Flask
FROM python:3.9-alpine

# Set the working directory
WORKDIR /app

COPY requirements.txt .

# Install Flask and other dependencies
RUN pip install -r requirements.txt

# Copy application code
COPY . .

# Run the application
CMD ["python", "app.py"]

